services:
  app:
    build: .
    env_file: .env
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 1.0.0.1
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.rtcam.rule=Host(`${HOST_DOMAIN}`)'
      - 'traefik.http.services.rtcam.loadbalancer.server.port=3000'
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true
